# Generated by Django 4.2 on 2025-06-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='data_atualizacao',
            new_name='atualizado_at',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='data_cadastro',
            new_name='criado_at',
        ),
    ]
