# Generated by Django 5.2.1 on 2025-09-10 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text='Código da ação (ex: PETR4.SA)', max_length=10, unique=True)),
                ('nome', models.CharField(help_text='Nome da empresa', max_length=200)),
                ('preco_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('variacao_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, help_text='Valor de mercado', null=True)),
                ('setor', models.CharField(blank=True, max_length=100, null=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
                'ordering': ['-market_cap'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(help_text='Quantidade de ações')),
                ('preco_compra', models.DecimalField(decimal_places=2, help_text='Preço médio de compra', max_digits=10)),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investimentos.acao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfólio do Usuário',
                'verbose_name_plural': 'Portfólios dos Usuários',
                'unique_together': {('usuario', 'acao')},
            },
        ),
    ]
