# Generated by Django 5.2.1 on 2025-06-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('email_contato', models.EmailField(blank=True, max_length=254, null=True)),
                ('recurso', models.CharField(max_length=255)),
                ('url_dados', models.URLField(blank=True, null=True)),
                ('url_consulta', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['nome'],
            },
        ),
    ]
