# Generated by Django 5.2.1 on 2025-06-30 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='bancos.banco')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bancos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Banco do Usuário',
                'verbose_name_plural': 'Bancos do Usuário',
                'unique_together': {('user', 'banco')},
            },
        ),
    ]
