# Generated by Django 5.2.1 on 2025-07-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0002_usuariobanco'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='tipo',
            field=models.CharField(choices=[('conta_corrente', 'Conta Corrente'), ('conta_poupanca', 'Conta Poupança'), ('conta_investimentos', 'Conta de Investimentos')], default='conta_corrente', max_length=50),
            preserve_default=False,
        ),
    ]
