# Generated by Django 5.2.1 on 2025-07-01 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0003_banco_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banco',
            old_name='email_contato',
            new_name='email',
        ),
    ]
