# Generated by Django 5.2.1 on 2025-06-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userperfil_bairro_alter_userperfil_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperfil',
            name='foto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
