# Generated by Django 5.2.1 on 2025-09-04 12:04

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userperfil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(help_text='CPF no formato 000.000.000-00', max_length=14, unique=True, validators=[users.models.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='data_nascimento',
            field=models.DateField(help_text='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Email único do usuário', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nome_completo',
            field=models.CharField(help_text='Nome completo do usuário', max_length=250),
        ),
    ]
